### ISSUE TITLE
遞迴只在天上有，凡人當用迴圈

### ISSUE THREAD

**Issue by MontyPan** [MontyPan/T-ccddcho#15]
# 名詞定義 #
遞迴（recursion / recursive，這是少數我改不過來會直接用翻譯的名詞 XD）的簡單定義是：**一個 method 的運作邏輯中包含了「call 自己」的部份。**

```Java
static void wtf() { wtf(); }

//只要有 call 到自己就算，所以這樣也還是遞迴
static void wtf2 { then(); }
static void then() { wtf2(); }
```

當然，上面這個除了示範遞迴跟製造 SOE（StackOverflowException，對，是同一個 stack，不要懷疑），沒啥屁用，因為根本沒有盡頭。

所以**真正的遞迴通常得包含終止條件：在什麼情況下不繼續遞迴下去。**（是不是跟迴圈很像呢... 可怕的數學家還會告訴你：「對喔，所有的迴圈都可以寫成遞迴」，不要問我怎麼證明的... 🙉 ）

在教學階段，能拿來有意義地示範遞迴的大概就是：費式數列、Quick Sort、Binary Tree traversal。

好的，來費事囉～～～ :dancer:

## ~~費事~~ 費式數列 

費式（Fibonacci）數列本身的定義就很直白地符合遞迴的要素。我這裡用的是無聊複雜版的費式數列定義，使用者可以自己決定 f(0) 跟 f(1) 的值：

```
n = 0, f(n) = x
n = 1, f(1) = y
n > 1, f(n) = f(n - 1) + f(n - 2)
(n < 0, don't care)
```

f(0) = 0, f(1) = 1 就是標準的費式數列：0, 1, 1, 2, 3, 5, 8, 13, 21, ......

# 需求 #

一樣不能用其他 class ~~（媽的這是還能用什麼 class... ）~~、一樣開一個 issue 專屬的 package，裡頭有：

+ `FibR` class，裡頭都是 static method，用遞迴的方式求 f(n)
+ `Fib1` class，標準 instance class，而且
    + 不能用遞迴
    + 不能宣告陣列
+ 只有 `main()` 的 `Tester` class

一樣提供 `Tester.main()` 的參考，沒有在上面限制的部份，都可自由修改成自己喜歡的形狀：

```Java
System.out.println(FibR.n(0, 1, 6));  //印出 8

Fib1 fib = new Fib(1, 2);  //給 f(0) 跟 f(1)
System.out.println(fib.n(4));  //還是印出 8
```

# 雜項提醒 #
你可以拆成兩個 2 PR，也就是說，寫完 `FibR` 的部份就可以發一個 PR，等到 accept 之後再做 `Fib1`。（對，PR 也可以小步前進）

還有，記得在發 PR 的時候報工時

**Comment by headinghome330** [comment]
請問這個 issue 一樣是在  ca3b607d 開 branch 嗎？

**Comment by MontyPan** [comment]
這個 case 無所謂（手臂強壯數的第二波 ~~疫情~~ 改版就有所謂），重點其實是「當有 PR accept，你要記得更新你的 local repo（的主要 branch）」

要認真說，這也只是一個好習慣、然後對於 git 新手來說可以少一些操作、也少一些 PR 炸 conflict 的機會，如此而已。

不然你早早就開始寫這個 issue，在 accept 之前 master 又多了好多 commit，以結果論來說還不是差不多.......

**Comment by MontyPan** [comment]
好 der... （好什麼，為什麼這個 issue 還沒結束？），現在是 optional 問題時間，你可以選擇要做 or 不做，不做的話請直接 close issue：

# 需求變更 #

現在你可以想用啥就用啥了，完全沒有任何限制（除了直接計算費式數列的 class / method XD），你能不能讓 class 版本（`Fib1`）整體的計算速度更快一點呢？

**Comment by MontyPan** [comment]
因為寫得有點多字，所以我 reopen issue，你看完請再度 close issue

--------------------------------------

# 回馬槍 feedback

後來補的 "需求變更" 就是設法讓你發現 "以空間換取時間"  的招數。 ~~因為泛綠的關係，我們不會把這招跟蔣介石的抗日戰爭策略扯上關係~~ 在資訊界裡頭，這樣的招數（應該）可以統稱 "cache 機制"

cache 機制真的無所不在，硬體上就一堆，我現在已經不知道 CPU 裡頭到底有幾層 cache 了（當年有 Lv2 的 CPU 是土豪才買得起），傳統硬碟也有 cache 叫做 buffer（SSD 應該不需要？）。

軟體的話當然也一堆，尤其是扯到網路。你跟網頁主機之間可能有：

+ browser cache
+ ISP proxy
+ 網站使用的 CDN
+ 網站程式系統內的..... [下略數百字]

你可以順便讀一下這篇，雖然現在後端應該不用直接面對了，但是書到用時恨少也來不及：http://blog.dontcareabout.us/2012/02/cache.html

喔對，寫程式的話不一定都是塞在記憶體，有的時候也會考慮存檔案 or 塞資料庫（browser cache 就是塞硬碟）

cache 機制自然是一種 trade-off，一定得衡量到底值得不值得。如果時間成本微不足道，大費周章搞這個也很奇怪，因為空間也不是無限大可以讓人隨便揮霍......

所以 cache 通常會是固定大小，然後有一套機制 / 演算法來決定塞滿的話那些東西會留在 cache 中、那些要丟掉..... 所以才會說 "cache 機制"

從這個角度來說，費式數列搞 cache 根本沒意義，計算的成本完全不值得犧牲空間（及其風險）來節省。

現實中比較會用到這招的是找質數，找質數的過程會反覆用到已知的質數，所以本來就需要存起來、算也要算很久所以值得存起來。而且還可以直接用 static（全宇宙的質數都一樣）.......

也是因為隨便 google 都會告訴你要用這招，也就只好拿費式數列來讓你費事了..... :dancer:

最後，"有沒有反過來用時間換空間的招數呢？"，因為時間是目前唯一買不到的 resource（idle game 都靠這個賺），所以相對少出現。我唯一能舉出來的就是 OS 裡頭的 virtual memory。

講這些單純是為了讓這個 issue 圓滿。這些回馬槍裡頭的名詞你有個基本印象即可...... 雖然我的 "有印象" 可能是你的 "讀好幾次說不定還要硬背下來"  [茶]
