### ISSUE TITLE
請用程式執行結果開示：為什麼不能這樣寫 for？

### ISSUE THREAD

**Issue by MontyPan** [MontyPan/T-ccddcho#18]
這是 #17 長出來的 issue，你寫了一個及其可怕的 for loop（L28）。

我說得長成這樣才對：

```Java
int wtf = power(10, l);
for (int k = (int) power(10, l - 1); k < wtf; k++) {
//skip
```

請找出原因，並另外設計一個盡可能精簡的程式來示範 / 說明 / 驗證這個原因。

# 注意 #

+ 程式碼直接擷取重點貼在 PR comment 就好，不用另外 commit。
+ 請先解決這個再回頭搞 #7 / #17

**Comment by headinghome330** [comment]
1. 讓 for 迴圈太複雜冗長。
2. 讓程式效率不好。當使用 for 迴圈，例如 `for( ; a < b ;)` ，需要滿足條件 a < b 才能繼續執行下去，或是範例中，
``` Java
int wtf = power(10, l);
for (int k = (int) power(10, l - 1); k < wtf; k++) {
```
如果直接將 power(10,l) 寫在 for 迴圈的條件裡面，代表每跑迴圈一次就要重新計算這個條件，以 wtf 代替這個數值的話，就只要計算一次。

如果以程式來測試效率（在 `main() ` 以 `test(8)` 執行），使用 variable 的效率會比較好，當位數越大差距就會越大，而如果是使用比 power() 更複雜的 method ，又不在迴圈的條件使用 variable ，就會讓程式效率更差。

- 條件為不使用變數代替
``` Java
public static void test(int t) {
	long startTime = System.currentTimeMillis();
	double s = power(10, t - 1);
	double f = power(10, t);
	for (double k = s; k < power(10, t); k++) {
		double min = (s + f) / 2;
		if (k == min) {
			System.out.println((int) k);
		}
	}
	long endTime = System.currentTimeMillis();
	System.out.println(endTime - startTime);
}
//平均為 550 - 650毫秒。
```
- 條件使用變數代替
``` Java
public static void test(int t) {
	long startTime = System.currentTimeMillis();
	double s = power(10, t - 1);
	double f = power(10, t);
	for (double k = s; k < f; k++) {
		double min = (s + f) / 2;
		if (k == min) {
			System.out.println((int) k);
		}
	}
	long endTime = System.currentTimeMillis();
	System.out.println(endTime - startTime);
}
//平均為 350 - 450毫秒。
```

**Comment by MontyPan** [comment]
嘖.... 你又在網路上亂狗了... 🙈  

好，先不管亂狗的事情。也先不管你的 1。

2 基本上是對的（除了廢話還是有點多，我實在不知道搞那個 `min = (s + f) / 2` 要幹麻）

我心目中理想的 [SSCCE] 是長這樣：

```Java
private static int foo() {
	System.out.println("call foo()");
	return 5;
}

public static void main(String[] args) {
	for (int i = 0; i < foo(); i++) {}
}
```

如此一來就能證明：`foo()` 的確會每一次 loop 都會重複 call。如果 `foo()` 要算很久（而且每次 loop 算出來的結果都一樣），那就會是沒有意義的浪費。

當然，這很可能是還沒最佳化的結果，實際執行時會不會被最佳化、會變成成什麼模樣，以我的技術能力是不會知道也不想知道... 🙉 ，直接拿出「預防勝於治療」這擋箭牌，在 source code 的源頭就控管好，一定不會有問題。

----------------------------------------------------------------------

以下是跟原始問題無關 ~~（對啦對啦，好啦我再講一次，你答對了喔，乖去旁邊玩）~~ ，而是在評論你的作答方式而不是答案本身。

首先，再抱怨一次，廢話太多。問題都這樣了，你就壓根不用去解釋「for loop」會是怎麼執行的。

你的 1 並不是那麼可靠。很多時候我們會抱怨寫成一行好難讀、但又有一堆時候我們會抱怨一堆變數好難讀（還要煩惱命名，所以也好難寫）。在你的 `armstrong()` case 中，我會傾向「不要抽出 `s` 還比較好讀」

然後，早在 n 年前（n > 10），就已經不太有人敢用 `System.currentTimeMillis()` 的方式來評估這種小規模的程式寫法優劣。原因是硬體太強大、OS 又太 multi 太多 background 程式（最近不是還炸出防毒軟體在挖礦的新聞 lol），所以一方面算出來的時間都很小、另一方面環境（OS）干擾又太多，兩邊夾擊下得到的數據幾乎沒啥說服力。

![](http://puui.qpic.cn/qqvideo_ori/0/v30306wh2jp_496_280/0)
多跑幾次阿，大人

嘿嘿，你真的給迴圈到一種境界（？），[JIT 可能還會出來做最佳化][JIT]，然後為了公平起見是不是還要先預熱（這不是唬爛，真有）....... [下略]

所以還是回到前面說的：預防勝於治療、源頭空管好比什麼都強。至於 `System.currentTimeMillis();` 這招，我建議你還是忘了吧....

最後，[SSCCE] 請務必了解一下，無論是在鬼打牆的時候、還是準備要罵人程式寫得爛的時候，「先寫個 SSCCE」拯救了我無數次... 直到今日都還是。你在上頭給的 code 連 SC 都沒有、更別說 short 了。

至於 [JIT] 那篇，看看有印象就好，看不懂... 也就這樣吧（我甚至都忘記我翻譯過這篇 XDDDD）


雖然 close 了，但是有要問問題還是什麼的，請自由往下蓋大樓。

[SSCCE]: http://sscce.org/
[JIT]: http://blog.dontcareabout.us/2013/03/jit-compiler.html
