### ISSUE TITLE
Spring 選書

### ISSUE THREAD

**Issue by MontyPan** [MontyPan/T-ccddcho#19]
**注意**：這是一個完全沒有強制性的建議（而且還扯到錢，雖然不是給我 XD），即便你要 reject 也沒問題。

因為你打算走後端，這部分我能力有限，至少無法像現在這樣作業隨心所欲亂出也沒問題。所以比較合理且有效率的方法就是先來本教材，然後看是要共讀還是怎麼的就再說。

於是我上天瓏找了一下，這兩三年出版的書中挑了這幾本：

+ https://www.tenlong.com.tw/products/9787517090557
+ https://www.tenlong.com.tw/products/9787115539441
+ https://www.tenlong.com.tw/products/9787302516446

進階 or 備選：

+ https://www.tenlong.com.tw/products/9787111692201
+ https://www.tenlong.com.tw/products/9787115499141

（對，基本上我會跳過實戰類的書）（對，找不到繁體中文。然後我不會假掰說去看原文書，更別說原文書都比較貴）

其實我不確定這些書是好是壞，純粹就網頁上提供的資訊判斷...... 🙈 

------------------

你依序可以做下列的決定，然後告訴我結論

0. 要不要搞這部分
1. 要不要買
2. 要不要去書店翻翻看
2. 要買哪一本，或是由我 ~~瞎子摸象地~~ 指定

當然你有更好的建議也歡迎提出。

然後，如果要買書，那就得在 01/18 之前決定書目。因為我家太座那幾天會上台北，可以幫我帶書回來（住鄉下又不想網購的痛苦 😭 ）

以上

**Comment by headinghome330** [comment]
好 👍 ，買書～
只是要買哪一本給 P 大你決定好了🤣～

p.s. 上一次 meeting 完後有去 Udemy 看課程，買了一個 270 元的 [課程](https://www.udemy.com/course/spring-hibernate-tutorial/)，但是是英文的(有字幕)，想說便宜就買來有空看 XD。

**Comment by MontyPan** [comment]
我本來的理想狀況是你去（天瓏）書店實際翻一翻買一買，然後再告訴我你選了那一本。（還是說你已經逃離台北了？ XD）

好吧，那就不囉唆，我選的是 [《Spring 5 高級編程》](https://www.tenlong.com.tw/products/9787302516446) 這本，你就去弄一本來吧。

----------------------------

這邊順便推幾本書，萬一要湊運費還是滿 xx 有折扣的話，可以考慮考慮（預防性利申：不管你在那家店買、買再多本也爽不到我）

+ [《Spring 實戰》](https://www.tenlong.com.tw/products/9787115527929)
    + 我選的那本應該是偏基礎理論，這本應該都是實際應用
    + 這樣想想，最上頭書單的 [這本](https://www.tenlong.com.tw/products/9787115539441) 也是偏應用... 真糟糕... 果然不應該用平板做正事... [扶額]
+ [《Effective Java》](https://www.tenlong.com.tw/products/9787111612728)

萬一這兩本都在天瓏買，現在有活動可以三本 7.5 折（1/31 前適用），那我可以搭便車湊一本《Effective Java》，至於怎麼給你錢 & 拿書就... 再說 XD


備註：天瓏當年是最有名的資訊類書店，現在應該也還是... 嗎？ 以前還在台北的時候，至少半年會去那裡晃一次，看看有什麼新書 & 現在流行什麼。如果你生活範圍也在台北的話，建議你也習慣性去走走

**Comment by headinghome330** [comment]
對，目前不在台北😅
有阿，以前去晃過一次了，不過那時候還沒開始寫程式😂
還是我就全部一起訂呀，再用超商交貨便或是其他方式送過去～

**Comment by MontyPan** [comment]
如果你有要加碼買我推薦的那兩本、外加湊三本打折，那就拜託幫我補上那本《Effective Java》。這本我不急（甚至不買都行 XD），所以有緣再面交之類的（而且我很討厭轉帳 Orz）

《Spring 5 高級編程》那本我想早點拿到（要是到時沒比你熟就搞笑啦 😱 ），而且反正太座是一定會上台北出差的，這樣大家都省錢省事。

**Comment by headinghome330** [comment]
剛剛已經拿到書了👍
有買推薦的那兩本
那 《Effective Java》要怎麼送到你那邊呢？
