### ISSUE TITLE
field 在哪裡 new instance 甘午差？

### ISSUE THREAD

**Issue by MontyPan** [MontyPan/T-ccddcho#44]
請找出（不是 primitive type 的）final instance field，「在宣告 field 時 new instance」跟「在 ctor 時 new instance」會有什麼不同，並且寫一個能展示出這個不同的 [SSCCE](http://sscce.org) 

從題目就應該看得出來，答案一定是 timing ~~（謎之聲：是喔... 我怎麼看不出來... [挖鼻孔]）~~ ，所以真正的問題 / 困難點是你要怎麼設計才有辦法呈現。

理論上你會需要（不需要也沒關係，說不定還有其他我不知道的哏）：

+ 搞出幾個 class
+ 搞出幾個 field

為了保險起見，你還是都寫成 public class，所以請記得放在 issue 對應的 package 底下

# 注意 #

+ field 宣告成 final 跟題目本身沒啥關係。要你宣告成 final 只是確保一定會 assign 到值、而且只會 assign 一次，如此而已。
+ 從此之後不要再跟我說 **你不知道什麼是 SSCCE**

**Comment by headinghome330** [comment]
目前寫成 breakfast、lunch、dinner 三個 class，裡面各自有寫 field ，以及 fee() method。
再寫 dailyFeeCtor 及 dailyFeeField 這兩個 class ，分別寫成 issue 規定的樣子。dailyFeeCtor 用 constructor 計算三餐的總和，dailyFeeField 使用 method 計算三餐的總和。再用 main 去 new instance，print 出兩個 method 的結果。
因為還找不到 timing 的差異，才還沒發 PR 😱

**Comment by MontyPan** [comment]
```mermaid
classDiagram
DailyFeeCtor *-- Breakfast
DailyFeeCtor *-- Lunch
DailyFeeCtor *-- Dinner
DailyFeeField *-- Breakfast
DailyFeeField *-- Lunch
DailyFeeField *-- Dinner
```

先別管什麼題目要求了，光這關係圖... 就哪裡 SSCCE 了？
